version: 2
jobs:
  abas:
    docker:
      - image: python:3.8

    steps:
    - checkout
    - run:
        name: SetUp_Lev
        command: |
          ls
         
          

    - run:
        name: SetUp_Go
        command: |
         
         
          ls

    - run:
        name: SetUp_Stop
        command: |
          ls
         
         






workflows:
  version: 2
  abas:
    jobs:
    - abas
